[package]
authors = ["The Servo Project Developers"]
build = "build.rs"
edition = "2018"
license = "MPL-2.0"
name = "simpleservo_jniapi"
publish = false
version = "0.0.1"

[lib]
bench = false
crate-type = ["cdylib"]
name = "simpleservo"
test = false

[dependencies]
android_injected_glue = "0.2"
android_logger = "0.10"
gstreamer = "0.15"
jni = "0.18.0"
libc = { workspace = true }
log = { workspace = true }
serde_json = { workspace = true }
simpleservo = { path = "../api" }

[build-dependencies]
cc = "1.0"

[features]
debugmozjs = ["simpleservo/debugmozjs"]
default = ["max_log_level", "native-bluetooth", "webdriver"]
googlevr = ["simpleservo/googlevr"]
js_backtrace = ["simpleservo/js_backtrace"]
max_log_level = ["simpleservo/max_log_level"]
media-gstreamer = ["simpleservo/media-gstreamer"]
native-bluetooth = ["simpleservo/native-bluetooth"]
webdriver = ["simpleservo/webdriver"]
webgl_backtrace = ["simpleservo/webgl_backtrace"]
