task:
  name: Windows
  windows_container:
    image: cirrusci/windowsservercore:visualstudio2019
    os_version: 2019
    cpu: 8
    memory: 32GB
    use_in_memory_disk: true
  env:
    CIRRUS_CLONE_DEPTH: 2
    PATH: C:\wix;$USERPROFILE\.cargo\bin;C:\Python\;$PATH
    PYTHON3: C:\Python\python.exe

  win_paths_workarounds_script:
    - fsutil behavior set disable8dot3 0
    - fsutil file setshortname "C:/Program Files (x86)/" PROGRA~2
    - fsutil file setshortname "C:/Program Files (x86)/Windows Kits/" wk~1
    - fsutil file setshortname "C:/Program Files (x86)/Microsoft Visual Studio" msvs
    - git config --system core.longpaths true  # Fix for windows git checkout problems
    - ps: New-ItemProperty -Path "HKLM:\SYSTEM\CurrentControlSet\Control\FileSystem" -Name "LongPathsEnabled" -Value 1 -PropertyType DWORD -Force
  install_gstreamer_script:
    - ps: Start-BitsTransfer -Source https://gstreamer.freedesktop.org/data/pkg/windows/1.16.0/gstreamer-1.0-msvc-x86_64-1.16.0.msi
    - ps: Start-Process msiexec.exe -Wait -ArgumentList "/i gstreamer-1.0-msvc-x86_64-1.16.0.msi /quiet /qn /norestart ADDLOCAL=ALL"
    - ps: Start-BitsTransfer -Source https://gstreamer.freedesktop.org/data/pkg/windows/1.16.0/gstreamer-1.0-devel-msvc-x86_64-1.16.0.msi
    - ps: Start-Process msiexec.exe -Wait -ArgumentList "/i gstreamer-1.0-devel-msvc-x86_64-1.16.0.msi /quiet /qn /norestart ADDLOCAL=ALL"
  wix311_binaries_script:
    - ps: Start-BitsTransfer -Source https://github.com/wixtoolset/wix3/releases/download/wix3111rtm/wix311-binaries.zip -Destination C:\wix311-binaries.zip
    - ps: Expand-Archive C:\wix311-binaries.zip -DestinationPath C:\wix
  rust_script:
    - ps: $ProgressPreference = "SilentlyContinue"; Invoke-WebRequest https://win.rustup.rs/ -OutFile rustup-init.exe; .\rustup-init.exe -y --default-host=x86_64-pc-windows-msvc --profile=minimal
  deps_script:
    - choco install -y python310 --params "/InstallDir:C:\Python"
  bootstrap_script:
    - python -m pip install --upgrade pip virtualenv
    - python mach fetch
  build_script:
    - python mach build --release -j 14
  smoke_test_script:
    - python mach smoketest --angle
  package_script:
    - python mach package --release
  win_artifacts:
    path: "target/release/msi/Servo.exe"
