tasks:
  - init: ./mach bootstrap # runs during prebuild
    command: ./mach run -r -Z disable-vsync
  
image:
  file: .gitpod.Dockerfile

ports:
  - port: 5900
    onOpen: ignore
  - port: 6080
    onOpen: open-preview
