[toolchain]
# Be sure to update etc/shell.nix when bumping this!
channel = "beta-2024-04-28"

components = [
    # For support/crown
    "llvm-tools",
    # For support/crown
    "rustc-dev",
    # For docs building
    "rust-docs",
    # For formatting
    "rustfmt",
]
profile = "minimal"
