[toolchain]
# Be sure to update etc/shell.nix when bumping this!
# Make sure to also update NIGHTLY_RUST in python/servo/platform/base.py
# with apropriate nightly version that corresponds to stable release
# (take a look at Branched from master date on https://releases.rs/docs/1.74.0/)
channel = "1.74"

components = [
    # For support/crown
    "llvm-tools",
    # For support/crown
    "rustc-dev",
    # For docs building
    "rust-docs",
    # For formatting
    "rustfmt",
]
profile = "minimal"
