# upstream files we should not format
exclude = ["third_party/**", "tests/**"]

[formatting]
align_comments = false
array_auto_collapse = false
array_auto_expand = false
column_width = 120
indent_string = "    "
reorder_keys = true
