version: 2.1
orbs:
  win: circleci/windows@5.0
jobs:
  build:
    executor: win/server-2019
    steps:
      - run: python -m pip install --upgrade pip virtualenv
      - run: python mach fetch
      - run: python mach build --release --media-stack=dummy
workflows:
  my-workflow:
    jobs:
      - build