version: 2.1
orbs:
  win: circleci/windows@5.0
jobs:
  build:
    executor: win/server-2019
    environment:
      CARGO_NET_GIT_FETCH_WITH_CLI: true
      PYTHON3: C:\tools\miniconda3\python.exe
    steps:
      - checkout
      - run: $ProgressPreference = "SilentlyContinue"; Invoke-WebRequest https://win.rustup.rs/ -OutFile rustup-init.exe; .\rustup-init.exe -y --default-host=x86_64-pc-windows-msvc --profile=minimal
      - run: python -m pip install --upgrade pip virtualenv
      - run: python mach fetch
      - run: python mach build --release --media-stack=dummy
workflows:
  my-workflow:
    jobs:
      - build