version: 2.1
orbs:
  win: circleci/windows@5.0
jobs:
  build:
    executor:
      name: win/server-2019
      size: large # 8 vCPU, 16GB ram
    environment:
      CARGO_NET_GIT_FETCH_WITH_CLI: true
      PYTHON3: C:\tools\miniconda3\python.exe
    steps:
      - checkout
      - run: $ProgressPreference = "SilentlyContinue"; Invoke-WebRequest https://win.rustup.rs/ -OutFile rustup-init.exe; .\rustup-init.exe -y --default-host=x86_64-pc-windows-msvc --profile=minimal
      - run: python -m pip install --upgrade pip virtualenv
      - run: python mach fetch
      - run:
          name: Build
          no_output_timeout: 2h # we will never hit that
          command: python mach build --release --media-stack=dummy -j16
workflows:
  my-workflow:
    jobs:
      - build