[package]
authors = ["The Servo Project Developers"]
description = "A fork of std::sync::Arc with some extra functionality and without weak references"
edition = "2018"
license = "MIT OR Apache-2.0"
name = "servo_arc"
repository = "https://github.com/servo/servo"
version = "0.2.0"

[lib]
name = "servo_arc"
path = "lib.rs"

[features]
gecko_refcount_logging = []
servo = ["serde"]

[dependencies]
nodrop = { version = "0.1.8" }
serde = { workspace = true, optional = true }
stable_deref_trait = "1.0.0"
