[package]
authors = ["The Servo Project Developers"]
edition = "2018"
license = "MPL-2.0"
name = "style_traits"
publish = false
version = "0.0.1"

[lib]
name = "style_traits"
path = "lib.rs"

[features]
gecko = []
servo = ["servo_atoms", "cssparser/serde", "webrender_api", "servo_url", "euclid/serde"]

[dependencies]
app_units = "0.7"
bitflags = "1.0"
cssparser = "0.29"
euclid = "0.22"
lazy_static = "1"
malloc_size_of = { path = "../malloc_size_of" }
malloc_size_of_derive = "0.1"
selectors = { path = "../selectors", features = ["shmem"] }
serde = "1.0"
servo_arc = { path = "../servo_arc" }
servo_atoms = { path = "../atoms", optional = true }
servo_url = { path = "../url", optional = true }
size_of_test = { path = "../size_of_test" }
to_shmem = { path = "../to_shmem" }
to_shmem_derive = { path = "../to_shmem_derive" }
webrender_api = { workspace = true, optional = true }
