[package]
authors = ["The Servo Project Developers"]
edition = "2018"
license = "MPL-2.0"
name = "to_shmem"
publish = false
version = "0.0.0"

[lib]
name = "to_shmem"
path = "lib.rs"

[features]
gecko = []
servo = ["cssparser/serde", "string_cache"]

[dependencies]
cssparser = { workspace = true }
servo_arc = { path = "../servo_arc" }
smallbitvec = { workspace = true }
smallvec = { workspace = true }
string_cache = { workspace = true, optional = true }
