[target.arm-linux-androideabi]
ar = "arm-linux-androideabi-ar"
linker = "./support/android/fakeld/fake-ld-arm.sh"

[target.armv7-linux-androideabi]
ar = "arm-linux-androideabi-ar"
linker = "./support/android/fakeld/fake-ld-armv7.sh"

[target.aarch64-linux-android]
ar = "aarch64-linux-android-ar"
linker = "./support/android/fakeld/fake-ld-arm64.sh"

[target.i686-linux-android]
ar = "i686-linux-android-ar"
linker = "./support/android/fakeld/fake-ld-x86.sh"

[target.arm-unknown-linux-gnueabihf]
ar = "arm-linux-gnueabihf-ar"
linker = "arm-linux-gnueabihf-gcc"

[target.aarch64-unknown-linux-gnu]
ar = "aarch64-linux-gnu-ar"
linker = "aarch64-linux-gnu-gcc"

[target.x86_64-pc-windows-msvc]
linker = "lld-link.exe"

[target.x86_64-uwp-windows-msvc]
linker = "lld-link.exe"

[target.i686-pc-windows-msvc]
linker = "lld-link.exe"

[target.aarch64-pc-windows-msvc]
linker = "lld-link.exe"

[target.aarch64-uwp-windows-msvc]
linker = "lld-link.exe"

[env]
MACOSX_DEPLOYMENT_TARGET = "10.10"

[build]
rustdocflags = ["--document-private-items"]
