[package]
authors = ["The Servo Project Developers"]
build = "build.rs"
description = "A GStreamer plugin that provides servosrc"
edition = "2018"
license = "MPL-2.0"
name = "servo-gst-plugin"
publish = false
repository = "https://github.com/servo/servo/"
version = "0.0.1"

[lib]
crate-type = ["cdylib"]
name = "gstservoplugin"
path = "lib.rs"

[dependencies]
crossbeam-channel = { workspace = true }
euclid = { workspace = true }
glib = "0.9"
gstreamer = "0.15"
gstreamer-base = "0.15"
gstreamer-gl = "0.15"
gstreamer-gl-sys = { version = "0.8", features = ["wayland"] }
gstreamer-sys = "0.8"
gstreamer-video = "0.15"
lazy_static = { workspace = true }
libservo = { path = "../../components/servo" }
log = { workspace = true }
servo-media = { git = "https://github.com/servo/media" }
sparkle = { workspace = true }
surfman = { workspace = true }
webxr = { git = "https://github.com/servo/webxr", features = ["glwindow"] }

[build-dependencies]
gst-plugin-version-helper = "0.2"
