[package]
authors = ["The Servo Project Developers"]
edition = "2018"
license = "MPL-2.0"
name = "size_of_test"
publish = false
version = "0.0.1"

[lib]
path = "lib.rs"

[dependencies]
static_assertions = "1.1"
