[package]
authors = ["The Servo Project Developers"]
edition = "2018"
license = "MPL-2.0"
name = "simpleservo_capi"
publish = false
version = "0.0.1"

[lib]
bench = false
crate-type = ["cdylib"]
name = "simpleservo"
test = false

[dependencies]
backtrace = { workspace = true }
env_logger = { workspace = true }
keyboard-types = { workspace = true }
lazy_static = { workspace = true }
log = { workspace = true }
simpleservo = { path = "../api" }
surfman = { workspace = true }

[target.'cfg(target_os = "windows")'.dependencies]
libc = { workspace = true }
winapi = { workspace = true, features = ["wingdi", "winuser", "winnt", "winbase", "processenv", "namedpipeapi", "ntdef", "minwindef", "handleapi", "debugapi"] }

[build-dependencies]
cbindgen = "0.26"

[features]
debugmozjs = ["simpleservo/debugmozjs"]
default = ["webdriver", "max_log_level"]
googlevr = ["simpleservo/googlevr"]
jitspew = ["simpleservo/jitspew"]
js_backtrace = ["simpleservo/js_backtrace"]
max_log_level = ["simpleservo/max_log_level"]
media-gstreamer = ["simpleservo/media-gstreamer"]
native-bluetooth = ["simpleservo/native-bluetooth"]
no-wgl = ["simpleservo/no-wgl"]
profilemozjs = ["simpleservo/profilemozjs"]
refcell_backtrace = ["simpleservo/refcell_backtrace"]
webdriver = ["simpleservo/webdriver"]
webgl_backtrace = ["simpleservo/webgl_backtrace"]
xr-profile = ["simpleservo/xr-profile"]
