[package]
authors = ["The Servo Project Developers"]
edition = "2018"
license = "MPL-2.0"
name = "style_derive"
publish = false
version = "0.0.1"

[lib]
path = "lib.rs"
proc-macro = true

[dependencies]
darling = { workspace = true, default-features = false }
derive_common = { path = "../derive_common" }
proc-macro2 = "1"
quote = "1"
syn = { version = "1", default-features = false, features = ["clone-impls", "derive", "parsing"] }
synstructure = "0.12"
