name: Mac workflow

on:
  workflow_call:
    inputs:
      layout:
        required: true
        type: string
      wpt:
        required: false
        type: string
      unit-tests:
        required: false
        default: false
        type: boolean
      upload:
        required: false
        default: false
        type: boolean
      github-release-id:
        required: false
        type: string
  workflow_dispatch:
    inputs:
      layout:
        required: true
        type: choice
        options: ["2013", "2020"]
      wpt:
        required: false
        type: string
      unit-tests:
        required: false
        default: false
        type: boolean
      upload:
        required: false
        default: false
        type: boolean
  push:
    branches: ["try-mac", "try-wpt-mac", "try-wpt-mac-2020"]

env:
  RUST_BACKTRACE: 1
  SHELL: /bin/bash
  LAYOUT: "${{ contains(inputs.layout, '2020') && 'layout-2020' || 'layout-2013' }}"
  PACKAGE: "${{ contains(inputs.layout, '2020') && 'mac-layout2020' || 'mac' }}"
  SCCACHE_GHA_ENABLED: "true"
  RUSTC_WRAPPER: "sccache"
  CCACHE: "sccache"
  CARGO_INCREMENTAL: 0

jobs:
  build-mac:
    name: Build
    runs-on: macos-12-xl
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 2
      - name: Run sccache-cache
        uses: mozilla-actions/sccache-action@v0.0.3
      - name: Bootstrap
        run: |
          python3 -m pip install --upgrade pip virtualenv
          python3 ./mach bootstrap-gstreamer
          brew install gnu-tar
      - name: Release build
        run: |
          python3 ./mach build --release --with-${{ env.LAYOUT }}
      - name: Smoketest
        run: python3 ./mach smoketest
      - name: Unit tests
        if: ${{ inputs.unit-tests }}
        run: python3 ./mach test-unit --release --with-${{ env.LAYOUT }}
      - name: Package
        run: python3 ./mach package --release
      - name: Package smoketest
        run: ./etc/ci/macos_package_smoketest.sh target/release/servo-tech-demo.dmg
      - name: Upload package
        uses: actions/upload-artifact@v3
        with:
          name: ${{ env.PACKAGE }}
          path: target/release/servo-tech-demo.dmg
      - name: Upload
        if: ${{ inputs.upload }}
        run: |
          python3 ./mach upload-nightly ${{ env.PACKAGE }} --secret-from-environment \
            --github-release-id ${{ inputs.github-release-id }}
        env:
          S3_UPLOAD_CREDENTIALS: ${{ secrets.S3_UPLOAD_CREDENTIALS }}
          GITHUB_HOMEBREW_TOKEN: ${{ secrets.HOMEBREW_TOKEN }}
          NIGHTLY_REPO_TOKEN: ${{ secrets.NIGHTLY_REPO_TOKEN }}
          NIGHTLY_REPO: ${{ github.repository_owner }}/servo-nightly-builds
      - name: Package binary
        run: gtar -czf target.tar.gz target/release/servo target/release/*.dylib resources
      - name: Archive binary
        uses: actions/upload-artifact@v3
        with:
          name: release-${{ env.LAYOUT }}-binary-macos
          path: target.tar.gz

  mac-wpt:
    if: ${{ github.ref_name == 'try-mac-wpt' || github.ref_name == 'try-mac-wpt-2020' || inputs.wpt }}
    name: Mac WPT Tests
    runs-on: macos-12-xl
    needs: ["build-mac"]
    env:
      max_chunk_id: 20
    strategy:
      fail-fast: false
      matrix:
        chunk_id: [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20]
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 2
      - uses: actions/download-artifact@v3
        with:
          name: release-${{ env.LAYOUT }}-binary-macos
      - name: Prep test environment
        run: |
          gtar -xzf target.tar.gz
          python3 -m pip install --upgrade pip virtualenv
          brew bundle install --verbose --no-upgrade --file=etc/homebrew/Brewfile
      - name: Smoketest
        run: python3 ./mach smoketest
      - name: Run tests
        run: |
          python3 ./mach test-wpt --with-${{ env.LAYOUT }} \
            --release $(sysctl -n hw.logicalcpu) --timeout-multiplier 4 \
            --total-chunks ${{ env.max_chunk_id }} --this-chunk ${{ matrix.chunk_id }} \
            --log-raw test-wpt.${{ matrix.chunk_id }}.log \
            --log-raw-unexpected unexpected-test-wpt.${{ matrix.chunk_id }}.log \
            --filter-intermittents filtered-test-wpt.${{ matrix.chunk_id }}.json
      - name: Archive filtered results
        uses: actions/upload-artifact@v3
        if: always()
        with:
          name: wpt-filtered-results-mac-${{ env.LAYOUT }}
          path: |
            filtered-test-wpt.${{ matrix.chunk_id }}.json
            unexpected-test-wpt.${{ matrix.chunk_id }}.log
      - name: Archive logs
        uses: actions/upload-artifact@v3
        if: failure()
        with:
          name: wpt-logs-mac-${{ env.LAYOUT }}
          path: |
            test-wpt.${{ matrix.chunk_id }}.log
            filtered-wpt-results.${{ matrix.chunk_id }}.json

  report-test-results:
    name: Reporting test results
    runs-on: ubuntu-latest
    if: ${{ always() && !cancelled() && success('build-mac') && (github.ref_name == 'try-mac-wpt' || github.ref_name == 'try-mac-wpt-2020' || inputs.wpt) }}
    needs:
      - "mac-wpt"
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 2
      - uses: actions/download-artifact@v3
        with:
          name: wpt-filtered-results-mac-${{ env.LAYOUT }}
          path: wpt-filtered-results-mac
      - name: Create aggregated unexpected results
        run: cat wpt-filtered-results-mac/*.log > unexpected-test-wpt.log
      - name: Archive aggregate results
        uses: actions/upload-artifact@v3
        with:
          name: wpt-filtered-results-mac-${{ env.LAYOUT }}
          path: |
            unexpected-test-wpt.log
      - name: Comment on PR with results
        run: etc/ci/report_aggregated_expected_results.py --tag="mac-wpt-${{ env.LAYOUT }}" wpt-filtered-results-mac/*.json
        env:
          GITHUB_CONTEXT: ${{ toJson(github) }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          RESULTS: ${{ toJson(needs.*.result) }}

  build_result:
    name: homu build finished
    runs-on: ubuntu-latest
    if: always()
    # needs all build to detect cancellation
    needs:
      - "build-mac"

    steps:
      - name: Mark the job as successful
        run: exit 0
        if: ${{ !contains(join(needs.*.result, ','), 'failure') && !contains(join(needs.*.result, ','), 'cancelled') }}
      - name: Mark the job as unsuccessful
        run: exit 1
        if: contains(join(needs.*.result, ','), 'failure') || contains(join(needs.*.result, ','), 'cancelled')
