name: Quick check
on:
  pull_request:
  push:
    branches:
      [ "**", "!master", "!auto", "!try", "!try-linux", "!try-mac", "!try-windows", "!try-wpt", "!dependabot/**"]

jobs:
  build-linux:
    name: Linux
    uses: ./.github/workflows/linux.yml
    with:
      layout: '2013'
      wpt: false
      unit: true
  build-linux-2020:
    name: Linux (layout-2020)
    uses: ./.github/workflows/linux.yml
    with:
      layout: '2020'
      wpt: false
      # TODO: unit tests on layout-2020
      unit: false